### ISSUE TITLE
Wrong selected objects

### ISSUE THREAD

**Issue by nicartograph** [ghtmtt/DataPlotly#77] opened 2018-05-02 09:35 UTC
Objects that are selected from a plot (Scatter Plot)  are not the same with selected by this action objects on a map.
Look at the pictures.
1. 
![image](https://user-images.githubusercontent.com/37081846/39515990-4f95166e-4e04-11e8-8f23-e4a0d2007909.png)
2.
![image](https://user-images.githubusercontent.com/37081846/39516103-9877390c-4e04-11e8-9e8d-9d2902672ea3.png)
3.
![image](https://user-images.githubusercontent.com/37081846/39516165-cd76af2a-4e04-11e8-9da2-99229fbe1d49.png)

Thank you!

P.S. I'm using QGIS 3.0.0 and Windows 10 Home
![image](https://user-images.githubusercontent.com/37081846/39516208-ea3c174e-4e04-11e8-97d0-1dc090a84116.png)

**Comment by ghtmtt** [comment] 2018-05-02 14:07
I cannot reproduce the error. But we can try to understand what is wrong. Can you create an additional column in the layer with unique id (using the function `$id` of the Field Calculator) and use this column to label the layer. Then try to redo the plot but add also the `Additional hovering label` in the second tab of DataPlotly setting it to the new id column. If the hovering label is the same of the label then something could be wrong with your setting (maybe refreshing the attribute table)
![selection_034](https://user-images.githubusercontent.com/2884884/39527874-df9e6396-4e22-11e8-91bb-90d2663870a2.png)

**Comment by nicartograph** [comment] 2018-05-02 14:37
Oh, I understood!
![image](https://user-images.githubusercontent.com/37081846/39529359-2563e3d6-4e2f-11e8-9a0d-f1eca3e96343.png)
I don't have 2 objects with 0 values on a plot. That's why we have this offset "2" in id value. Perhaps, you have some secial condition for zero in attributes?

**Comment by ghtmtt** [comment] 2018-05-03 07:06
I have some special method for `NULL`, but wait.. Now you are using plotly default button to selected the data (the second upper button from the right). What if you choose the other method clicking on the other button? Maybe some queries are overlapping some points on the x axis

![selection_035](https://user-images.githubusercontent.com/2884884/39563587-198b6dae-4eb1-11e8-9652-c4854e7a9b31.png)

**Comment by nicartograph** [comment] 2018-05-03 18:33
Nope, nothig's changed. I can't find these two objects with 0 values.
But! I found them after changing attributes for X and Y axes. So, zero values are not visualized on Y, but visualized on X.

**Comment by ghtmtt** [comment] 2018-05-05 08:03
mmm still I cannot reproduce the error.. see the picture.. 

![selection_043](https://user-images.githubusercontent.com/2884884/39661030-8a3a809e-504b-11e8-808e-133f3c1404ad.png)

**Comment by nicartograph** [comment] 2018-05-05 12:08
But I still have the same. I don't understand:) Ok, I think thant it's my own problem, I'll deal with it, huge thanks to you!

**Comment by ghtmtt** [comment] 2018-05-05 12:45
still weird ;) can you attach you data so I can it a try and hopefully understand what's wrong?

**Comment by nicartograph** [comment] 2018-05-05 12:51
Only if you want it so much :) Hope it's data problem.
[weird_watersheds.zip](https://github.com/ghtmtt/DataPlotly/files/1976668/weird_watersheds.zip)

**Comment by ghtmtt** [comment] 2018-05-05 13:32
Nope, I get the correct data selected in plot - canvas and attribute table

![selection_044](https://user-images.githubusercontent.com/2884884/39663762-7a571bc8-5079-11e8-891a-619d5b6e95df.png)

**Comment by nicartograph** [comment] 2018-05-05 13:35
Apparently the problem in me :)
![image](https://user-images.githubusercontent.com/37081846/39663792-4ae86f46-5082-11e8-96a4-6a476c5c6ccd.png)

**Comment by ghtmtt** [comment] 2018-05-15 12:36
@nicartograph I'm closing this issue because it seems related to your data and not to the plugin itself. Fell free to reopen it or to report other issues. Thanks for testing

**Closed by ghtmtt** 2018-05-15 12:36 UTC

**Comment by daniel-childs** [comment] 2018-10-03 19:52
Hey @ghtmtt, I seem to be running into the same problem as @nicartograph. There ARE null values in my data, but not the columns that are being plotted. Potentially something where the any rows with null values are being dropped at some point? The attached screenshot shows the interpreted y value for the particular data point.
![image](https://user-images.githubusercontent.com/4240758/46434775-78caf480-c709-11e8-85b9-6bb394ccbf17.png)
