### ISSUE TITLE
Geopackage Views seem not to work, or is the DateTime column?

### ISSUE THREAD

**Issue by rduivenvoorde** [ghtmtt/DataPlotly#224] opened 2020-05-08 14:43 UTC
Not sure if I do something wrong or if I hit an issue:

Trying to create a scatter/line plot from a view from a Geopackage (Time-Value) where Time is a DateTime do not show up in DataPlotly:

![Screenshot-20200508163103-1269x910](https://user-images.githubusercontent.com/731673/81415923-5735b880-9149-11ea-8ae9-5fae96003dec.png)

While the underlying data-table does this fine:

![Screenshot-20200508162937-1265x906](https://user-images.githubusercontent.com/731673/81415744-22c1fc80-9149-11ea-8999-896a11b375ad.png)

**To Reproduce**
1. From this zipped geopackage: [cloud3.zip](https://github.com/ghtmtt/DataPlotly/files/4599597/cloud3.zip) load both the data table and the view4
2. View4 is actually a view/join from Data and Grid
3. Try to create a scatterplot from Data: works fine: as you see Value are actually VERY small values (from 1E-10 till 10 or so...)
4. Then try to do this with the view4 layer: not sure what goes wrong, but the Y-axis is going from 0-4 but nothing is shown
5. Note that I actually wanted (as this is time related data) see a plot of one cell (this is air dispersion modelling).. Also @ghtmtt interest probably: https://github.com/qgis/QGIS/issues/36291 and https://github.com/qgis/QGIS/issues/26804 I created the view with 'OGC_FID' and then selection works \o/
6. Note that is also seems that for the view the DateTime (Time) column seems not to be reckognized?

**Desktop (please complete the following information):**
 - OS: Debian Testing
 - QGIS master
 - DataPlotly current

**Comment by ghtmtt** [comment] 2020-05-08 15:23
Hey Richard. mmmm not able to reproduce the issue. I downloaded the geopackage and the `Time` columns is correctly read as Time by QGIS and DataPlotly from the view4 table.

I created a scatter plot Time vs Value and these are the results:

![image](https://user-images.githubusercontent.com/2884884/81420373-2dcc5b00-9150-11ea-93c7-d0c719138571.png)

![image](https://user-images.githubusercontent.com/2884884/81420452-43da1b80-9150-11ea-8278-422cde78605e.png)

Also with very small values:

![image](https://user-images.githubusercontent.com/2884884/81420516-5c4a3600-9150-11ea-8613-740037f4a5df.png)

Date, time, datatime issues have been fixed some time ago with #194. Is the widget showing the correct value (Time) of the column (as it appear in the screenshot?)

BTW: thanks for the links of the QGIS upstream issues ;)

**Comment by rduivenvoorde** [comment] 2020-05-08 15:58
Thanks @ghtmtt  for testing!
Argh, now it works with me to (I reinstalled the plugin to be honest...).

One thing I note (not DataPlotly related!) is that if you check the 'only selected features', and you click(!) in the most left cell, only one feature is selected:

![Screenshot-20200508175233-1593x856](https://user-images.githubusercontent.com/731673/81423584-f0b69780-9154-11ea-80c4-c97db29f30dd.png)

While if you draw a small box it it, all features below are selected:

![Screenshot-20200508175254-1590x846](https://user-images.githubusercontent.com/731673/81423599-f7450f00-9154-11ea-8573-d0444584b638.png)

Is this how QGIS selecting normally works?

@nyalldawson @ghtmtt  note that the new temporal features in QGIS for vector in combination with DataPlotly is a very very nice data visualisation tool!! Thanks all!

**Comment by ghtmtt** [comment] 2020-05-08 16:25
> @nyalldawson @ghtmtt note that the new temporal features in QGIS for vector in combination with DataPlotly is a very very nice data visualisation tool!! Thanks all!

ultra-combo + fatality :) this is worth a tweet or something similar

I'm closing the issue, feel free to reopen it

**Closed** 2020-05-08 16:26 UTC
Labels: bug
