### ISSUE TITLE
Selection doesn't work well with gpkg vectors

### ISSUE THREAD

**Issue by pigreco** [ghtmtt/DataPlotly#236] opened 2020-09-19 16:39 UTC
By selecting the chart, the features in the map canvas are not the correct ones but select the previous feature.

how to play:

1. create a new **geopakage** and import into a vector,
2. create a bar chart,
3. select a graph bar
4. the selection in the map canvas is not correct

I attach gpkg

NB: **with a shapefile it works**

![image](https://user-images.githubusercontent.com/7631137/93671903-0941a180-faa7-11ea-871f-795a71e9b80c.png)

![image](https://user-images.githubusercontent.com/7631137/93671909-1494cd00-faa7-11ea-8b73-92018d28dbf1.png)

![image](https://user-images.githubusercontent.com/7631137/93671925-32fac880-faa7-11ea-86ee-6278d31a1a9a.png)

[test.zip](https://github.com/ghtmtt/DataPlotly/files/5250172/test.zip)

![image](https://user-images.githubusercontent.com/7631137/93672058-2c208580-faa8-11ea-968e-0b4615ef6eda.png)

**Comment by bellanz80** [comment] 2020-09-19 17:33
I confirm. 
I have tested with another geopack (EPGS 6372) and I get the same erroneous behavior.
But, I noticed that the error seems to be using the selection tools (box or lasso select), because if I select with the cursor it works correctly.
I attach a video where it is noted that: when clicking on the highest bar, the state of "Chihuahua" is selected, correct. But if it is selected with the box select, the state of "Chiapas" is selected, which in the list is exactly the preceding (-1) to Chihuahua. (can be seen on the X axis of the graph)

![2020-09-19_12h25_01](https://user-images.githubusercontent.com/38449926/93681808-efd33200-fa73-11ea-9b3c-32c559618e81.gif)

annex also data

[stati_messicani.zip](https://github.com/ghtmtt/DataPlotly/files/5250275/stati_messicani.zip)

**Comment by ghtmtt** [comment] 2020-09-23 05:56
so it seems a geopackage related issue. Could you make a test also with a SpatiaLite? Thanks!

**Comment by pigreco** [comment] 2020-09-23 11:50
I confirm problems also with spatialite vectors


![image](https://user-images.githubusercontent.com/7631137/94008737-c7b13f00-fda3-11ea-8f9d-e262fd62a551.png)

**Comment by ghtmtt** [comment] 2020-09-28 07:52
OK the problem IS related with sqlite like dataset because of the index starting number. I've a patch ready but I'm unsure how solid it is.

**Comment by ghtmtt** [comment] 2022-04-13 08:15
closing this issue because is strictly dependent on the data provider

**Closed by ghtmtt** 2022-04-13 08:15 UTC
Labels: bug
