### ISSUE TITLE
DataPlotly not plotting.

### ISSUE THREAD

**Issue by philippHRO** [ghtmtt/DataPlotly#85] opened 2018-11-01 09:49 UTC
DataPlotly isn't plotting for me. The plugin-panel lets me choose the layer and X-Field, Y-Field and so on, but the Plot stays empty. 
I installed QGIS Desktop 3.4.0 with GRASS 7.4.2 via OSGeo4W. I used a very simple Shapfile (see image) and also tested a GeoPackage layer.

What can i do, to make it work?

![grafik](https://user-images.githubusercontent.com/23098362/47844760-81275580-ddc3-11e8-9e8f-e9bd5b0d9b18.png)

 

--------------
QGIS version | 3.4.0-Madeira | QGIS code revision | 4a4b62ed19
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.0-CAPI-1.11.0 | Running against GEOS | 3.7.0-CAPI-1.11.0 673b9939
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

**Comment by ghtmtt** [comment] 2018-11-05 11:11
That's really strange. Could you share a piece of the dataset? I cannot reproduce the error.

**Comment by philippHRO** [comment] 2018-11-05 13:43
This is the tiny .gpkg i created. 
[test.zip](https://github.com/ghtmtt/DataPlotly/files/2548611/test.zip)

**Comment by ghtmtt** [comment] 2018-11-05 17:44
Cannot reproduce, here the plot.

![selection_127](https://user-images.githubusercontent.com/2884884/48015995-5706c800-e122-11e8-953c-1e11428a01a6.png)

Which version of Dataplotly are you using?

**Comment by philippHRO** [comment] 2018-11-06 07:59
2.0
I installed it via the plugin browser in QGIS
![grafik](https://user-images.githubusercontent.com/23098362/48050463-439b4180-e1a2-11e8-937b-67e831c1122d.png)

**Comment by philippHRO** [comment] 2018-11-06 08:17
I just discovered the DataPlotly Tool "Build a generic plot", which I had not activated before. I tested it and an error came up (see below), maybe it's what causing the problem in the DataPlotly Panel as well?

I also realized, it might be a problem for QGIS/dataplotly, that my userdata is sitting on a network drive. Is there a way to define a local folder for plugins?

`Processing algorithm…
Algorithm 'Build a generic plot' starting…
Input parameters:
{ 'INPUT' : 'N:/Daten_GG/UAV/FHHProjekt/AP3/Wuchshoehen/RTK_Buffer_10cm.shp', 'IN_COLOR' : 0, 'IN_COLOR_HTML' : '', 'OUTPUT_HTML_FILE' : 'C:/Users/philipp/AppData/Local/Temp/processing_d1743f5688f747b8b2d563aa25c62385/89eed528ef4a41b3a5e6f0c7ce9b9d84/OUTPUT_HTML_FILE.html', 'OUTPUT_JSON_FILE' : 'C:/Users/philipp/AppData/Local/Temp/processing_d1743f5688f747b8b2d563aa25c62385/091f482690e64892a95488501bdf8720/OUTPUT_JSON_FILE.json', 'PLOT_TITLE' : 'test', 'PLOT_TYPE' : 0, 'XFIELD' : 'WHD', 'YFIELD' : 'S_10cm_mea' }

Traceback (most recent call last):
File "//servername.de/homes/profile/philipp/Anwendungsdaten/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\processing\dataplotly_algorithms.py", line 281, in processAlgorithm
standalone_plot_path = plot_instance.buildFigure()
File "//servername.de/homes/profile/philipp/Anwendungsdaten/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\data_plotly_plot.py", line 651, in buildFigure
fig = go.Figure(data=self.trace, layout=self.layout)
File "C:\PZ\OSGeo4W\apps\Python37\lib\site-packages\plotly\graph_objs\_figure.py", line 380, in __init__
super(Figure, self).__init__(data, layout, frames, skip_invalid)
File "C:\PZ\OSGeo4W\apps\Python37\lib\site-packages\plotly\basedatatypes.py", line 139, in __init__
skip_invalid=skip_invalid)
File "C:\PZ\OSGeo4W\apps\Python37\lib\site-packages\_plotly_utils\basevalidators.py", line 2075, in validate_coerce
v_el = v_el.to_plotly_json()
File "C:\PZ\OSGeo4W\apps\Python37\lib\site-packages\plotly\basedatatypes.py", line 3398, in to_plotly_json
return deepcopy(self._props if self._props is not None else {})
File "C:\PZ\OSGeo4W\apps\Python37\lib\copy.py", line 150, in deepcopy
y = copier(x, memo)
File "C:\PZ\OSGeo4W\apps\Python37\lib\copy.py", line 240, in _deepcopy_dict
y[deepcopy(key, memo)] = deepcopy(value, memo)
File "C:\PZ\OSGeo4W\apps\Python37\lib\copy.py", line 150, in deepcopy
y = copier(x, memo)
File "C:\PZ\OSGeo4W\apps\Python37\lib\copy.py", line 215, in _deepcopy_list
append(deepcopy(a, memo))
File "C:\PZ\OSGeo4W\apps\Python37\lib\copy.py", line 169, in deepcopy
rv = reductor(4)
TypeError: can't pickle QVariant objects

Execution failed after 4.53 seconds

Loading resulting layers
Algorithm 'Build a generic plot' finished
HTML output has been generated by this algorithm.
Open the results dialog to check it.`

**Comment by ghtmtt** [comment] 2018-11-06 08:30
That's pretty weird too. But let's try to proceed step by step:

which version of plotly have you installed? Just open a python console in QGIS and type:

```
import plotly
plotly.__version__
```

**Comment by philippHRO** [comment] 2018-11-06 08:48
'3.3.0'

**Comment by ghtmtt** [comment] 2018-11-06 09:11
OK, then in QGIS/Processing maybe there is something that should be updated. 

I'm pretty sure that the main issue is related, as you suggested, that you have local and network installation:

> Traceback (most recent call last):
> File "//servername.de/homes/profile/philipp/Anwendungsdaten/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\processing\dataplotly_algorithms.py", line 281, in processAlgorithm
> standalone_plot_path = plot_instance.buildFigure()

in which directory are all the QGIS plugins installed?

**Comment by philippHRO** [comment] 2018-11-06 09:40
I guess that would be 
`\\servername.de\homes\profile\philipp\Anwendungsdaten\QGIS\QGIS3\profiles\default\python\plugins\`

**Comment by ghtmtt** [comment] 2018-11-06 10:04
mmm I suspect that the reason is definitely that one. Don't know ho w to solve it in an easy way

**Comment by philippHRO** [comment] 2018-11-06 10:08
Ok i will see, if I can somehow define a local profile folder.

**Comment by philippHRO** [comment] 2018-11-09 14:57
Ok it's working now. To everyone, who encountered this, use the parameter --profiles-path "dir" to set a new folder for qgis3 to store its profiles. Set this folder to a local directory.

DataPlotly is plotting now that my profile is in a local folder.

**Comment by ghtmtt** [comment] 2018-11-09 18:51
glad that you solved the problem. I'll close the issue. Thanks for the advice

**Closed by ghtmtt** 2018-11-09 18:51 UTC
