### ISSUE TITLE
If I select another line in a layer, subdiagrams are removed, and only the latest, single diagram, is shown.

### ISSUE THREAD

**Issue by CvTooren** [ghtmtt/DataPlotly#265] opened 2021-09-20 11:52 UTC
**Bug**
If I select another line in a layer subdiagrams are removed, and only the latest, single diagram, is shown.

**To Reproduce**
I have made a test csv layer with two lines  (a road with data in two directions (AB and BA)) and data of two variables (integers) intensity and weight which are measured for 4 years (2018 until 2021).
 
![afbeelding](https://user-images.githubusercontent.com/11072582/133997172-bd1f8500-5753-4640-88c7-f45726bd4270.png)

I fill in the dataplotly fields
 
 
![afbeelding](https://user-images.githubusercontent.com/11072582/133997209-c7edb385-1c5b-49c0-94eb-9cca9e295ed8.png)

![afbeelding](https://user-images.githubusercontent.com/11072582/133997246-c50056fb-aa37-422a-ae37-7c52127e0296.png)

And then make diagram with the make diagram button
The result is a nice diagram
 
![afbeelding](https://user-images.githubusercontent.com/11072582/133997276-5740d8bd-fb7b-4451-b3c9-b3d12f45f84d.png)

If I select the other direction the diagram (yellow line) the graph is updated nicely.

Then I add the Weight variable with the Make diagram button
![afbeelding](https://user-images.githubusercontent.com/11072582/133997305-1ac99d21-530f-41d9-b0df-7086e0046d03.png)
 

The result is nice with the two variable graphs besides each other (notice the different Y values)
 
![afbeelding](https://user-images.githubusercontent.com/11072582/133997352-4b6885ed-19a8-49f3-91ab-1902e944cf47.png)

( I had expected another color of the line, but that's not a to big problem)

If I now select the other direction (other line) the result is:
 
![afbeelding](https://user-images.githubusercontent.com/11072582/133997440-c17069f7-20be-4996-a707-5b26b1b8d7b1.png)

I had hoped/expected that both diagrams would be updated and now **_only_** the Weight variable graph is shown

****OS***
Windows 10, latest version
QGIS 3.20.2
DataPlotly 3.7.1

**Additional context**
If I make a shp file form the csv file and use that layer the results are the same

I hope everything is clear. Support is much appreciated in this very nice plug-in.
Regards Coen

**Comment by ghtmtt** [comment] 2022-04-13 07:54
that's by design. If you click on `Update` only the last plot is updated. We don't have a method (yet) to selectively update the single plots:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2884884/163127849-d0142aa9-8307-4248-8fae-58c2a381d93f.gif)

I'm closing this issue. Please reopen of file a feature request if necessary. Thanks for reporting!

**Closed** 2022-08-24 12:56 UTC
Labels: bug
