### ISSUE TITLE
Label size on Pie chart

### ISSUE THREAD

**Issue by githubnagib** [ghtmtt/DataPlotly#247] opened 2021-02-19 06:19 UTC
Is it possible to change label size on Pie chart? When I put chart on qgis Layout, labels are too small, and useless.

**Comment by ghtmtt** [comment] 2021-02-19 07:08
not yet. Maybe a duplicate of #232?

**Comment by ghtmtt** [comment] 2021-03-19 11:00
I'm closing this as a duplicate of #232

**Closed by ghtmtt** 2021-03-19 11:00 UTC
Labels: enhancement
