### ISSUE TITLE
bug in Processing for Plot type: scatter

### ISSUE THREAD

**Issue by AndreasRabe** [ghtmtt/DataPlotly#92] opened 2019-03-08 16:22 UTC
Processing algorithm…
Algorithm 'Build a generic plot' starting…
Input parameters:
{ 'INPUT' : 'C:/Users/janzandr/Downloads/sampled.gpkg|layername=sampled', 'IN_COLOR' : 0, 'IN_COLOR_HTML' : '', 'OUTPUT_HTML_FILE' : 'TEMPORARY_OUTPUT', 'OUTPUT_JSON_FILE' : 'TEMPORARY_OUTPUT', 'PLOT_TITLE' : '', 'PLOT_TYPE' : 0, 'XFIELD' : 'fraction_1', 'YFIELD' : 'fraction_3' }

Traceback (most recent call last):
File "C:/Users/janzandr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DataPlotly\processing\dataplotly_algorithms.py", line 296, in processAlgorithm
f.write(json.dumps(ojson))
File "C:\OSGEO4~1\apps\Python37\lib\json\__init__.py", line 231, in dumps
return _default_encoder.encode(obj)
File "C:\OSGEO4~1\apps\Python37\lib\json\encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "C:\OSGEO4~1\apps\Python37\lib\json\encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "C:\OSGEO4~1\apps\Python37\lib\json\encoder.py", line 179, in default
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Scatter is not JSON serializable

Execution failed after 2.89 seconds

Loading resulting layers
Algorithm 'Build a generic plot' finished
HTML output has been generated by this algorithm.
Open the results dialog to check it.

**Comment by ghtmtt** [comment] 2019-03-08 16:29
@mdouchin some months ago plotly updated to version 3 (currently 3.6 is used in QGIS) and they made some small API changes. Do you mind to have a small look at this?

**Comment by ghtmtt** [comment] 2020-08-14 13:21
duplicate of the more recent #234.

**Closed by ghtmtt** 2020-08-14 13:21 UTC
Labels: bug
