### ISSUE TITLE
Additional hover label on/off

### ISSUE THREAD

**Issue by dusanm92** [ghtmtt/DataPlotly#227] opened 2020-05-16 09:32 UTC
When using "Bar plot" is it possible to turn off "Additional hover label"? I populated that field, and now I can't make it blank, when I delete column name it populates it again automatically, maybe it is a small bug.

![additional hover label](https://user-images.githubusercontent.com/65444804/82116248-a9d62c80-9768-11ea-9942-bca2cc57403d.jpg)

 - OS: Windows 10
 - QGIS release QGIS 3.4 and QGIS 3.10, both LTR
 - DataPlotly release 3.7.1

**Comment by ghtmtt** [comment] 2020-08-14 15:21
You can simply delete the field of the `Additional hovering label` combobox and the numbers disappear from the plot. This combobox supports empty values, therefore you can pass an empty string. I'm closing the issue since it is not a bug. Please reopen if necessary and thanks for reporting the issue

**Closed by ghtmtt** 2020-08-14 15:21 UTC
Labels: bug
