### ISSUE TITLE
Error installing on an old version of Windows Server

### ISSUE THREAD

**Issue by mtreg** [ghtmtt/DataPlotly#235] opened 2020-09-08 02:20 UTC
**Describe the bug**
When trying to install from the Plugins repository in a desktop environment within Windows Server (2012 R2) I get the following error: "This Windows version (6.3.9600) does not support the required Bluetooth API. Consider updating to a more recent Windows (10.0.10586 or above)."

**To Reproduce**
1. Within Windows Server 2012 R2, go to install the Data Plotly plugin via the plugin manager.
2. See error

**Screenshots**
All text that appeared is in the bug description.

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2
 - e.g. QGIS 3.10 and QGIS 3.12
 - Latest Data Plotly release (may apply to older releases as well)

**Additional context**
I realize it might be a very specific OS issue, but since the error was regarding a bluetooth API, which would seem irrelevant for this Plug-in, figured I'd file this bug report and see if it's something easily managed - if so, great! If not, no worries.

Thank you so much for your work! This plug-in is great!
Mike

**Comment by ghtmtt** [comment] 2020-09-09 06:41
I think it is a duplicate of the closed issue https://github.com/GIS4WRF/gis4wrf/issues/103. Can you test it?

**Comment by mtreg** [comment] 2020-09-13 02:10
Thanks @ghtmtt! I'll see if I can test, but due to permissions and administration, might not be able to.  But the solution to test would be renaming the dll as described [here](https://github.com/GIS4WRF/gis4wrf/issues/103#issuecomment-575889035)?  Or is there something

**Comment by ghtmtt** [comment] 2020-09-14 12:51
@mtreg I cannot test it since I don't have a Windows machine.

**Comment by ghtmtt** [comment] 2020-11-10 14:04
please reopen if necessary

**Closed by ghtmtt** 2020-11-10 14:04 UTC
Labels: bug, feedback
