### ISSUE TITLE
get_symbol_color() not working

### ISSUE THREAD

**Issue by katagen** [ghtmtt/DataPlotly#299] opened 2022-08-21 14:57 UTC
I'm trying to use the new `get_symbol_color`, but I can't make it works?
Did you have an exemple how to use it? Cause everything stays in the "default blue"...

**Comment by ghtmtt** [comment] 2022-08-21 15:28
the expression takes the colors of the features on the map and applies them in the plot:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2884884/185798564-f25b5d9e-9ac2-4566-8b33-f34af9a86e3c.gif)

**Comment by katagen** [comment] 2022-08-21 16:38
Here is a screenrecord:
![screen](https://user-images.githubusercontent.com/37768582/185801533-17df3680-d9ae-4927-a98e-9918acc420c9.gif)

**Comment by ghtmtt** [comment] 2022-08-22 08:58
ok maybe there is an old bug not related to this new feature. In the DataPlotly panel, can you click on the layer again to select it? I see that in the expression editor no features are found and therefore plotly is applying the standard light blue color

**Comment by katagen** [comment] 2022-08-22 09:51
Ok, when I try to go into the edit panel again, it write "invalid expression", with `unable to convert a C++ 'QPointer' instance to a Python object`.
![Capture](https://user-images.githubusercontent.com/37768582/185893200-def6ceb4-c0e7-408c-b29f-6cefd6076593.JPG)

**Comment by katagen** [comment] 2022-08-22 09:55
And it does that for polygons, points and lines... I can use the expression and at first it writes "no features are found", and if I go again in the editor, then "invalid expression".

**Comment by ghtmtt** [comment] 2022-08-22 12:08
I cannot replicate the issue. If you choose the layer again in the combobox, in my case for all the vector layers, whatever style and categorization I choose, I get the color and no error. 

Can you maybe share the project?

**Comment by katagen** [comment] 2022-08-22 14:25
You can find it [here](https://drive.google.com/file/d/1GeQsmNjrazVTu506LSCoKBmhton_gtl4/view?usp=sharing)!

**Comment by katagen** [comment] 2022-08-22 15:15
Tested on 4 different machines, all on 3.22. It never works, either for polygons, lines or points. I use temporary layer, shapfiles and geopackage layer... no success?!?
On 2 machines, I installed QGIS from scratch!

**Comment by ghtmtt** [comment] 2022-08-23 08:51
sorry but still I cannot reproduce the bug:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2884884/186115534-a73b8cb2-a4f2-4bcf-88a5-baad0d34ceca.gif)

**Comment by katagen** [comment] 2022-08-23 11:12
OK, but I re-install QGIS, and still not working?!?
What does it mean: `unable to convert a C++ 'QPointer' instance to a Python object`?

**Comment by katagen** [comment] 2022-08-23 12:39
I asked 4 colleagues to test the plugin (MacOS and Windows). Also not working: `no features are found`.

**Comment by ghtmtt** [comment] 2022-08-24 05:52
> I asked 4 colleagues to test the plugin (MacOS and Windows). Also not working: no features are found.

for this you just have to re-click o the vector layer in the combobox as I said. The bug should be fixed and a new release is coming soon.

>  What does it mean: unable to convert a C++ 'QPointer' instance to a Python object? As you can see, I have this error!

Sorry but here I am lost. It's the first time I see this error

**Comment by katagen** [comment] 2022-08-24 09:08
> for this you just have to re-click o the vector layer in the combobox as I said. The bug should be fixed and a new release is coming soon.
Hope the update will do it, cause it changes nothing if I re-select the layer in the combobox.

> Sorry but here I am lost. It's the first time I see this error.
The first time I enter the expression editor, it says `no feature found`. But if I re-enter the expression editor, after generated the plot, it says `invalid expression` with this message.

**Comment by ghtmtt** [comment] 2022-08-24 10:03
not sure, but can you try a QGIS version >= 3.24? Maybe it has something to do with this bug: https://github.com/qgis/QGIS/issues/48090

**Comment by katagen** [comment] 2022-08-24 10:59
You are right... I installed 3.26 on one computer, and it works!

**Comment by ghtmtt** [comment] 2022-08-24 12:25
great!

**Closed by ghtmtt** 2022-08-24 12:25 UTC
Labels: feedback

**Comment by katagen** [comment] 2022-08-24 12:43
Just a last question, this means that the expression won't be available for the LTR (3.22), or you'll find a solution for the upcoming update? Cause I need to "stay" on LTR version at work... it is just to know ;-)

**Comment by ghtmtt** [comment] 2022-08-24 12:52
The bug was fixed for QGIS >= 3.24. You have to wain until the next LTR release: https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release

**Comment by jonath35** [comment] 2023-01-06 14:33
Hello,
It doesn't look ok for histogram plot. Qgis 3.28.1 or Qgis 3.22
![Sans titre](https://user-images.githubusercontent.com/91737794/211032588-dadeaf3b-21b2-4397-8e0a-b08b81e81503.png)
