### ISSUE TITLE
Couldn't load plugin 'DataPlotly' 

### ISSUE THREAD

**Issue by ChinookJargon** [ghtmtt/DataPlotly#171] opened 2019-11-21 22:48 UTC
Hello I am new to QGIS and am struggling to get Data Plotly plugin installed on my laptop.
Python version: 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609] 
QGIS version: 3.4.4-Madeira Madeira, f6ddc62 

When I try loading the DataPlotly plugin I get the following message:
```
Couldn't load plugin 'DataPlotly' 

UnicodeEncodeError: 'latin-1' codec can't encode character '\u25b2' in position 1516186: ordinal not in range(256) 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/__init__.py", line 25, in 
    from .data_plotly import DataPlotly
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/data_plotly.py", line 31, in 
    from DataPlotly.gui.dock import DataPlotlyDock
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/dock.py", line 14, in 
    from DataPlotly.gui.plot_settings_widget import DataPlotlyPanelWidget
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/gui/plot_settings_widget.py", line 73, in 
    from DataPlotly.core.plot_factory import PlotFactory
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/jr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DataPlotly/core/plot_factory.py", line 14, in 
    import plotly
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/plotly/__init__.py", line 31, in 
    from plotly import (plotly, graph_objs, grid_objs, tools, utils, session,
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/plotly/plotly/__init__.py", line 10, in 
    from . plotly import (
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/plotly/plotly/plotly.py", line 31, in 
    from plotly import exceptions, tools, utils, version, files
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/plotly/tools.py", line 20, in 
    from plotly import graph_reference
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3/dist-packages/plotly/graph_reference.py", line 518, in 
    GRAPH_REFERENCE = get_graph_reference()
  File "/usr/lib/python3/dist-packages/plotly/graph_reference.py", line 86, in get_graph_reference
    sha1 = hashlib.sha1(six.b(str(graph_reference))).hexdigest()
  File "/usr/lib/python3/dist-packages/six.py", line 620, in b
    return s.encode("latin-1")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u25b2' in position 1516186: ordinal not in range(256)
```

Any insight you might have about how to resolve this issue would be greatly appreciated!

**Comment by ghtmtt** [comment] 2019-12-17 16:18
Is this issue still valid? I cannot reproduce the error.

**Comment by ghtmtt** [comment] 2020-02-05 17:09
you can try with the updated version of the plugin. Closing the issue due to missing feedback

**Closed by ghtmtt** 2020-02-05 17:09 UTC

**Comment by gvanhavre** [comment] 2020-04-17 10:50
Hello, I've got the exact same problem as above when trying to install the plugin from the repository. I'm on Linux Mint 18.3, with QGIS 3.4.10 and Python 3.5.2.

And when trying to install from the zip, i gives me:

pyplugin_installer.instance().installFromZipFile(r'/home/****/DataPlotly-master.zip')
traceback.print_exception() failed

**Comment by ghtmtt** [comment] 2020-04-17 10:56
> Hello, I've got the exact same problem as above when trying to install the plugin from the repository. I'm on Linux Mint 18.3, with QGIS 3.4.10 and Python 3.5.2.

also with the updated version of DataPlotly released yesterday (3.6.)? BTW: I recommend to update also QGIS to at least 3.10 or 3.12

**Comment by gvanhavre** [comment] 2020-04-17 11:11
I'll update and post a feedback.

**Comment by gvanhavre** [comment] 2020-04-17 21:35
I updated to Mint 19 and QGIS 3.10. Now it works like a charm. Thanks!

**Comment by ghtmtt** [comment] 2020-04-18 07:15
great!
