### ISSUE TITLE
Color scale is empty when using assistant for data defined marker color

### ISSUE THREAD

**Issue by jdugge** [ghtmtt/DataPlotly#164] opened 2019-11-05 18:34 UTC
When using the expression assistant to generate the expression for a data defined marker color, the resulting plot has an empty color scale.

Also, the Color Scale selected in the DataPlotly combobox is ignored. This makes sense, since the color scale is instead defined in the expression assistant, but it is still confusing.

![2019-11-05_19-30-25](https://user-images.githubusercontent.com/2399255/68235246-30b08c80-0003-11ea-9bd9-543b1eff5e71.gif)

**Comment by ghtmtt** [comment] 2019-11-07 17:29
duplicate of #165

**Closed by ghtmtt** 2019-11-07 17:29 UTC
